version: '3'

services:
  nsqlookupd:
    container_name: nsqlookupd
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160
      - 4161:4161
    restart: on-failure
  nsqd:
    container_name: nsqd
    image: nsqio/nsq
    # Note: one might need to add nsqd to the hosts file
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151
    restart: on-failure
  nsqadmin:
    container_name: nsqadmin
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171
    restart: on-failure
